### ISSUE TITLE
REDIS_URL without creds causes a crash

### ISSUE THREAD

**Issue by bgentry** [ryansmith3136/l2met#31]
``` bash
$ REDIS_URL=redis://localhost:6379 APP_NAME=l2met.local LOCAL_WORKERS=2 l2met 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x349a0]

goroutine 1 [running]:
l2met/utils.init·1()
    /Users/bgentry/go/src/l2met/utils/redis.go:20 +0x173
l2met/utils.init()
    /Users/bgentry/go/src/l2met/utils/utils.go:110 +0x6d
main.init()
    /Users/bgentry/go/src/l2met/main.go:0 +0x54

goroutine 2 [syscall]:
created by runtime.main
    /Users/bgentry/Code/go--hg/src/pkg/runtime/proc.c:221

$ REDIS_URL=redis://u:p@localhost:6379 APP_NAME=l2met.local LOCAL_WORKERS=2 l2met 
Postgres has been disabled.
at=start-l2met port=8000
```

Coming from this line:

``` go
    password, set := u.User.Password()
```

**Comment by ryansmith3136** [comment]
Tracking fix in #33.
