### ISSUE TITLE
Cannot start the app: App Crashed: Heroku H10 errors

### ISSUE THREAD

**Issue by davestern** [ryansmith3136/l2met#57]
Followed the basic instructions in the README and used OpenRedis:

REDIS_URL: redis://:password@1.2.3.4:11856

(password and ip changed)

No other configs are set.

I cannot start the app without H10 errors. Errors in the logs:

`2013-05-01T18:58:00.074300+00:00 heroku[web.1]: Starting process with command`l2met`
2013-05-01T18:58:00.099901+00:00 heroku[librato_outlet.1]: Starting process with command`librato_outlet`
2013-05-01T18:58:00.789910+00:00 app[web.1]: panic: fernet: key decodes to wrong size
2013-05-01T18:58:00.789910+00:00 app[web.1]:
2013-05-01T18:58:00.789910+00:00 app[web.1]: goroutine 1 [running]:
2013-05-01T18:58:00.790150+00:00 app[web.1]: github.com/kr/fernet.MustDecodeKeys(0xf8400686d0, 0x100000001, 0x5f8df4, 0x3a00000001, 0xf8400686d0, ...)
2013-05-01T18:58:00.790150+00:00 app[web.1]:    /tmp/build_3muhzg1dajk5b/.heroku/g/src/github.com/kr/fernet/key.go:78 +0x9e
2013-05-01T18:58:00.790150+00:00 app[web.1]: l2met/utils.init·1()
2013-05-01T18:58:00.790270+00:00 app[web.1]:    /tmp/build_3muhzg1dajk5b/.heroku/g/src/l2met/utils/auth.go:20 +0x79
2013-05-01T18:58:00.790363+00:00 app[web.1]: l2met/utils.init(0x40e5e3, 0x40d107, 0x0, 0x0, 0x40e572, ...)
2013-05-01T18:58:00.790426+00:00 app[web.1]:    /tmp/build_3muhzg1dajk5b/.heroku/g/src/l2met/utils/utils.go:100 +0x77
2013-05-01T18:58:00.790426+00:00 app[web.1]: main.init()
2013-05-01T18:58:00.790520+00:00 app[web.1]:    /tmp/build_3muhzg1dajk5b/.heroku/g/src/l2met/main.go:0 +0x54
2013-05-01T18:58:00.790520+00:00 app[web.1]:
2013-05-01T18:58:00.790520+00:00 app[web.1]: goroutine 2 [syscall]:
2013-05-01T18:58:00.790637+00:00 app[web.1]: created by runtime.main
2013-05-01T18:58:00.790637+00:00 app[web.1]:    /usr/local/go/src/pkg/runtime/proc.c:221
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]: panic: fernet: key decodes to wrong size
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]:
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]: goroutine 1 [running]:
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]: github.com/kr/fernet.MustDecodeKeys(0xf8400696d0, 0x100000001, 0x5fc24c, 0x3a00000001, 0xf8400696d0, ...)
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]:         /tmp/build_3muhzg1dajk5b/.heroku/g/src/github.com/kr/fernet/key.go:78 +0x9e
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]: l2met/utils.init·1()
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]:         /tmp/build_3muhzg1dajk5b/.heroku/g/src/l2met/utils/auth.go:20 +0x79
2013-05-01T18:58:00.828430+00:00 app[librato_outlet.1]: l2met/utils.init(0x40e965, 0x40d489, 0x0, 0x0, 0x40e8f4, ...)
2013-05-01T18:58:00.828835+00:00 app[librato_outlet.1]:         /tmp/build_3muhzg1dajk5b/.heroku/g/src/l2met/utils/utils.go:100 +0x77
2013-05-01T18:58:00.828835+00:00 app[librato_outlet.1]: main.init()
2013-05-01T18:58:00.828835+00:00 app[librato_outlet.1]:         /tmp/build_3muhzg1dajk5b/.heroku/g/src/l2met/librato_outlet/main.go:0 +0x54
2013-05-01T18:58:00.828835+00:00 app[librato_outlet.1]:
2013-05-01T18:58:00.828835+00:00 app[librato_outlet.1]: goroutine 2 [syscall]:
2013-05-01T18:58:00.828835+00:00 app[librato_outlet.1]: created by runtime.main
2013-05-01T18:58:00.828835+00:00 app[librato_outlet.1]:         /usr/local/go/src/pkg/runtime/proc.c:221
2013-05-01T18:58:01.999250+00:00 heroku[web.1]: Process exited with status 2
2013-05-01T18:58:02.161098+00:00 heroku[librato_outlet.1]: Process exited with status 2
2013-05-01T18:58:02.013500+00:00 heroku[web.1]: State changed from starting to crashed
2013-05-01T18:58:02.712904+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path=/logs host=l2met-sphere.herokuapp.com fwd="54.242.116.105" dyno= connect= service= status=503 bytes=
2013-05-01T18:58:02.904465+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path=/logs host=l2met-sphere.herokuapp.com fwd="50.16.29.124" dyno= connect= service= status=503 bytes=
2013-05-01T18:58:02.628296+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path=/logs host=l2met-sphere.herokuapp.com fwd="184.73.115.129" dyno= connect= service= status=503 bytes=
2013-05-01T18:58:03.048053+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path=/logs host=l2met-sphere.herokuapp.com fwd="50.16.29.124" dyno= connect= service= status=503 bytes=`

**Comment by ryansmith3136** [comment]
Thanks for the report. Can you try this as a workaround:

``` bash
$ heroku config:set SECRETS=$(dd if=/dev/urandom bs=32 count=1 2>/dev/null | openssl base64)
```

**Comment by davestern** [comment]
That works! Thanks.

**Comment by ryansmith3136** [comment]
I have updated the install instruction to reflect this step. Thanks for reporting.
